addons:
  postgresql: 11.2
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database lol_champs_test;' -U postgres
language: ruby
rvm:
  - 2.4.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
